CREATE DATABASE OPTUS;

USE OPTUS;

CREATE TABLE Artistas
(
	idArtista INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL
);

CREATE TABLE Albuns
(
	idAlbum INT PRIMARY KEY IDENTITY
	,idArtista INT FOREIGN KEY REFERENCES Artistas(idArtista)
	,Titulo VARCHAR(250) NOT NULL
	,DataLancamento VARCHAR(10) NOT NULL
	,Localizacao VARCHAR(250) NOT NULL
	,QtdMinutos VARCHAR(2) NOT NULL
	,Ativo VARCHAR(3) NOT NULL
);

CREATE TABLE Estilo
(
	idEstilo INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(100) NOT NULL
);

CREATE TABLE AlbunsEstilo
(
	idAlbum INT FOREIGN KEY REFERENCES Albuns(idAlbum)
	,idEstilo INT FOREIGN KEY REFERENCES Estilo(idEstilo)
);

CREATE TABLE Usuarios
(
	idUsuario INT PRIMARY KEY IDENTITY
	,Nome VARCHAR(200) NOT NULL
	,Email VARCHAR(200) NOT NULL
	,Senha VARCHAR(6) NOT NULL
	,Permissao VARCHAR(200) NOT NULL
);
